cmake_minimum_required(VERSION 3.10)
project(agent)
set(CMAKE_CXX_STANDARD 20)
add_library(agent_lib STATIC src/agent/agent.cpp)
target_include_directories(agent_lib PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/src)
# target_link_libraries(my_lib PUBLIC pthread)
add_compile_options(-Wall -Wextra -Wpedantic)
add_executable(agent src/main.cpp)
target_link_libraries(agent PRIVATE agent_lib)
